### PR TITLE
upd 0.2

### LINKED ISSUE #2: Current version doesn't support python 3
Current version (0.1) doesn't support python 3. But 0.2 version on pypi does support python 3.

### PR DESCRIPTION
**Pull request by kiwi0fruit**
closes https://github.com/conda-forge/sphinxcontrib-restbuilder-feedstock/issues/2

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
@conda-forge-admin, please rerender

**Comment by kiwi0fruit** [comment]
@conda-forge-admin @conda-forge/help-python please merge PR.

**Comment by kiwi0fruit** [comment]
@ocefpaf Could you please merge PR

**Comment by kiwi0fruit** [comment]
@beckermr please PR

**Comment by beckermr** [comment]
I cannot merge here. For feedstocks, you should ask the maintenance team directly.

@conda-forge/sphinxcontrib-restbuilder

**Comment by kiwi0fruit** [comment]
OK thanks anyway.

**Comment by kiwi0fruit** [comment]
@scopatz could you please merge this PR

**Comment by kiwi0fruit** [comment]
@holgern please merge this PR.

**Comment by scopatz** [comment]
I'll merge tomorrow if @holgern hasn't responded.

**Comment by kiwi0fruit** [comment]
Thanks.

**Pull request merged**
